### ISSUE TITLE
RN 0.52 编译报错

### ISSUE THREAD

**Issue by 25juan** [tokinonagare/react-native-http-cache2#1]
E:\react-native\lgzq\node_modules\react-native-http-cache2\android\src\main\java\cn\reactnative\httpcache\HttpCacheModule.java:69: 错误: 找不到符号
        FileCache cache1 = ImagePipelineFactory.getInstance().getMainDiskStorageCache();
                                                             ^
  符号:   方法 getMainDiskStorageCache()
  位置: 类 ImagePipelineFactory
E:\react-native\lgzq\node_modules\react-native-http-cache2\android\src\main\java\cn\reactnative\httpcache\HttpCacheModule.java:80: 错误: 找不到符号
        FileCache cache2 = ImagePipelineFactory.getInstance().getSmallImageDiskStorageCache();
                                                             ^
  符号:   方法 getSmallImageDiskStorageCache()
  位置: 类 ImagePipelineFactory
2 个错误

**Comment by tokinonagare** [comment]
> https://github.com/reactnativecn/react-native-http-cache/issues/23

参考原库中提出的解决方法

https://github.com/tokinonagare/react-native-http-cache2/commit/bc9a6b650959bda0de019f27a27fc7d37ee14925

> https://github.com/facebook/fresco/blob/df630d25e5e6899ee85b09ed296beaa4725e1a75/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineFactory.java

能看到, 'getMainDiskStorageCache' 'getMainDiskStorageCache' 已经没有了
